### ISSUE TITLE
update readme file

### ISSUE THREAD

**Issue by BorisKGB** [BorisKGB/git_test_repo#1]

**Comment by flotsky** [comment]
start doing...

**Comment by flotsky** [comment]
Add changes in request https://github.com/BorisKGB/git_test_repo/pull/2

**Comment by BorisKGB** [comment]
add something else to description

**Comment by flotsky** [comment]
update https://github.com/BorisKGB/git_test_repo/pull/2

**Comment by BorisKGB** [comment]
well done, merging into main...

**Comment by BorisKGB** [comment]
merged, no errors
